version: '3.1'
services:
  rabbit:
    image: rabbitmq:3-management
    environment:
       RABBITMQ_DEFAULT_USER: user
       RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
      - "5672:5672"